---
title: "ML Predictor Dataset Cleaning"
author: "Will Thackway"
date: "01/07/2021"
output: html_document
---

############ 0. Setup ###################
# 0.0 Packages
```{r setup, include=FALSE}
library(sf)
library(dplyr)
library(MLmetrics)
library(mapview)
library(ExcelFunctionsR)

library(raster)
library(geomerge)
library(maptools)
library(tidyverse)
library(lwgeom)
library(plyr)
library(tmap)
library(ggplot2)
library(reshape2)
library(maptools)
library(rgdal)
library(zoo)

library(classInt)
library(Hmisc)
```




############ 1. Import Data ###################
# 1.0 SEIFA scores
```{r}
SEIFA_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_SEIFA.csv", stringsAsFactors = FALSE)

SEIFA_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_SEIFA.csv", stringsAsFactors = FALSE)
```

# 1.1 Census Data
```{r}
## 2011 Datasets
age_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_Age.csv", stringsAsFactors = FALSE)

cob_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_COB.csv", stringsAsFactors = FALSE)

dwelling_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_Dwelling.csv", stringsAsFactors = FALSE)

education_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_Education Level.csv", stringsAsFactors = FALSE)

employment_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_Employment Status.csv", stringsAsFactors = FALSE)

family_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_Family Composition.csv", stringsAsFactors = FALSE)

hours_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_Hours Worked.csv", stringsAsFactors = FALSE)

income_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_Median Income.csv", stringsAsFactors = FALSE)

industry_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_Industry.csv", stringsAsFactors = FALSE)

marital_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_Marital Status.csv", stringsAsFactors = FALSE)

migration_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_Migration.csv", stringsAsFactors = FALSE)

occupation_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_Occupation.csv", stringsAsFactors = FALSE)

population_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_Population.csv", stringsAsFactors = FALSE) %>% mutate(SA1_MAIN11 = sa1_code)

religion_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_Religion.csv", stringsAsFactors = FALSE)

tenure_11  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2011 Census Data/CSV Processed Inputs/2011_SA1_Tenure.csv", stringsAsFactors = FALSE)




## 2016 Datasets
age_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_Age.csv", stringsAsFactors = FALSE)

cob_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_COB.csv", stringsAsFactors = FALSE)

dwelling_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_Dwelling.csv", stringsAsFactors = FALSE)

education_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_Education Level.csv", stringsAsFactors = FALSE)

employment_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_Employment Status.csv", stringsAsFactors = FALSE)

family_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_Family Composition.csv", stringsAsFactors = FALSE)

hours_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_Hours Worked.csv", stringsAsFactors = FALSE)

income_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_Median Income.csv", stringsAsFactors = FALSE)

industry_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_Industry.csv", stringsAsFactors = FALSE)

marital_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_Marital Status.csv", stringsAsFactors = FALSE)

migration_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_Migration.csv", stringsAsFactors = FALSE)

occupation_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_Occupation.csv", stringsAsFactors = FALSE)

population_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_Population.csv", stringsAsFactors = FALSE)

religion_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_Religion.csv", stringsAsFactors = FALSE)

tenure_16  <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/2016 Census Data/CSV Processed Inputs/2016_SA1_Tenure.csv", stringsAsFactors = FALSE)
```


# 1.2 Non-Census Data
```{r}
## 2011
abb_11 <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/Non-Census Data/CSV_Processed_Inputs/2011_SA1_ABB.csv")

abr_11 <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/Non-Census Data/CSV_Processed_Inputs/2011_SA2_ABR.csv")

commercial_11 <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/Non-Census Data/CSV_Processed_Inputs/2011_SA1_Commercial.csv")

infra_11 <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/Non-Census Data/CSV_Processed_Inputs/2011_SA1_Infrastructure.csv")

property_11 <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/Non-Census Data/CSV_Processed_Inputs/2011_SA1_Property.csv") %>% 
  mutate(property_house_number_sales = IFNA(property_house_number_sales, 0),
         property_unit_number_sales = IFNA(property_unit_number_sales, 0))

walk_11 <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/Non-Census Data/CSV_Processed_Inputs/2011_SA1_Walkability.csv")



## 2016
abb_16 <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/Non-Census Data/CSV_Processed_Inputs/2016_SA1_ABB.csv")

abr_16 <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/Non-Census Data/CSV_Processed_Inputs/2016_SA2_ABR.csv")

commercial_16 <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/Non-Census Data/CSV_Processed_Inputs/2016_SA1_Commercial.csv")

infra_16 <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/Non-Census Data/CSV_Processed_Inputs/2016_SA1_Infrastructure.csv")

property_16 <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/Non-Census Data/CSV_Processed_Inputs/2016_SA1_Property.csv") %>% 
  mutate(property_house_number_sales = IFNA(property_house_number_sales, 0),
         property_unit_number_sales = IFNA(property_unit_number_sales, 0))

walk_16 <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/Non-Census Data/CSV_Processed_Inputs/2016_SA1_Walkability.csv")
```


# 1.3 Import Mappings
```{r}
# SA1 11 -> 16 mapping
sa1_mapping <- read.csv("C:/Files/Value Australia/All_Projects/Data/Mappings/SA1 Mapping.csv", stringsAsFactors = FALSE, fileEncoding="UTF-8-BOM")
```



######### 2. Merge Datasets ##########
# 2.1 Merge Predictor Variables
```{r}
# 2011
data_11 <- age_11 %>%
# Census Data
  merge(cob_11, by="SA1_MAIN11") %>% 
  merge(dwelling_11, by="SA1_MAIN11") %>% 
  merge(education_11, by="SA1_MAIN11") %>%
  merge(employment_11, by="SA1_MAIN11") %>%
  merge(family_11, by="SA1_MAIN11") %>%
#  merge(household_11, by="SA1_MAIN11") %>%
  merge(income_11, by="SA1_MAIN11") %>%
  merge(industry_11, by="SA1_MAIN11") %>%
  merge(marital_11, by="SA1_MAIN11") %>%
  merge(migration_11, by="SA1_MAIN11") %>%
  merge(occupation_11, by="SA1_MAIN11") %>%
  merge(population_11, by="SA1_MAIN11") %>%
  merge(religion_11, by="SA1_MAIN11") %>%
  merge(tenure_11, by="SA1_MAIN11") %>%
# SA1 mapping 
  merge(sa1_mapping, by="SA1_MAIN11") %>%           
# Non-Census data
  merge(abb_11, by="SA1_MAIN16") %>% 
  merge(abr_11, by="SA1_MAIN16") %>% 
  merge(commercial_11, by="SA1_MAIN16") %>% 
  merge(infra_11, by="SA1_MAIN16") %>% 
  merge(property_11, by="SA1_MAIN16") %>% 
  merge(walk_11, by="SA1_MAIN16") %>% 
# Drop NA's
  drop_na()

data_11_test <- data_11[!duplicated(data_11$SA1_MAIN16),]


# 2016
data_16 <- age_16 %>%
# Census Data
  merge(cob_16, by="SA1_MAIN16") %>% 
  merge(dwelling_16, by="SA1_MAIN16") %>% 
  merge(education_16, by="SA1_MAIN16") %>%
  merge(employment_16, by="SA1_MAIN16") %>%
  merge(family_16, by="SA1_MAIN16") %>%
#  merge(household_16, by="SA1_MAIN16") %>%
  merge(income_16, by="SA1_MAIN16") %>%
  merge(industry_16, by="SA1_MAIN16") %>%
  merge(marital_16, by="SA1_MAIN16") %>%
  merge(migration_16, by="SA1_MAIN16") %>%
  merge(occupation_16, by="SA1_MAIN16") %>%
  merge(population_16, by="SA1_MAIN16") %>%
  merge(religion_16, by="SA1_MAIN16") %>%
  merge(tenure_16, by="SA1_MAIN16") %>%
# Non-Census data
  merge(abb_16, by="SA1_MAIN16") %>% 
  merge(abr_16, by="SA1_MAIN16") %>% 
  merge(commercial_16, by="SA1_MAIN16") %>% 
  merge(infra_16, by="SA1_MAIN16") %>% 
  merge(property_16, by="SA1_MAIN16") %>% 
  merge(walk_16, by="SA1_MAIN16") %>% 
# Drop NA's
  drop_na()

data_16_test <- data_16[!duplicated(data_16$SA1_MAIN16),]


# write.csv(data_11_all, "C:/Files/Value Australia/Gentrification ML Prediction/Data/Outputs/Data_11_All.csv")
```


# 2.2 Merge SEIFA data
```{r}
# 2011 - Merge 2011 Predictor Variables to 2016 SEIFA score: ultimately we will use 2011 X to predict 2016 Y
data_11_SEIFA <- data_11 %>% 
  merge(SEIFA_11, by="SA1_MAIN11") %>% 
  merge(SEIFA_16, by="SA1_MAIN16") %>%
  mutate(irsad_score_11 = irsad_score.x,
         irsad_score_16 = irsad_score.y) %>% 
  dplyr::select(-c(sa1_code, SA1_MAIN11, airbnb_share, national_rank.x, national_rank.y, irsad_score.x, irsad_score.y, X.x, X, X.y))

data_11_SEIFA_final <- data_11_SEIFA[!duplicated(data_11_SEIFA$SA1_MAIN16),]

# 2016 - Don't merge on SEIFA score to 2016 dataset: ultimately we will use 2016 X to predict 2021 (unknown) Y
data_16_SEIFA <- data_16 %>% 
  merge(SEIFA_16, by="SA1_MAIN16") %>%
  dplyr::select(-c(area_sqkm, airbnb_share, national_rank, X.x, X.y, X))

data_16_SEIFA_final <- data_16_SEIFA[!duplicated(data_16_SEIFA$SA1_MAIN16),] 

# Test merging the two datasets to see how many SA1 areas compatible with both datasets
data_all_SEIFA <- merge(data_11_SEIFA_final, data_16_SEIFA_final, by="SA1_MAIN16") %>% drop_na()
```


# 2.3 Export Complete Dataset
```{r}
write.csv(data_11_SEIFA_final, "C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/Cleaned Datasets/Data_11_SEIFA_final.csv")

write.csv(data_16_SEIFA_final, "C:/Files/Value Australia/Gentrification ML Prediction/Data/Inputs/Cleaned Datasets/Data_16_SEIFA_final.csv")
```