---
title: "ML Housing Price Data Prep"
author: "Will Thackway"
date: "02/07/2021"
output: html_document
---

############ 0. Setup ###################
# 0.0 Import packages
```{r setup}
library(sf)
library(dplyr)
library(MLmetrics)
library(mapview)

library(raster)
library(geomerge)
library(maptools)
library(tidyverse)
library(lwgeom)
library(plyr)
library(tmap)
library(ggplot2)
library(reshape2)
library(maptools)
library(rgdal)
library(zoo)

library(classInt)
library(Hmisc)
library(ExcelFunctionsR)
```

# 0.1 Assumption setting
```{r}
# Inflation Rate
inf_rate <- 0.025

# Property Count Threshold
pct <- 10
```



############ 1. Import & Clean Data ###################
# 1.1 Import Data, inflate property price 
```{r}
## Sold Data
da_raw <- read.csv("C:/Files/Value Australia/Gentrification ML Prediction/Data/Validation/All_DA_Records_Export-210414.csv")
```


# 1.2 Merge dataset with SA1 => to get SA1 column
```{r}
# Import SA1 esri shapefile boundaries
# Import Statistical Area boundaries
unzip("C:/Files/Value Australia/All_Projects/Data/Inputs/1270055001_sa1_2016_aust_shape.zip", exdir=".")
sa1 <- read_sf("SA1_2016_AUST.shp") %>% filter(GCC_CODE16 == "1GSYD") %>% st_transform(crs = st_crs(4283))

# Convert data to spatial data frame using property latitude and longitude
da_sf <- da_raw %>% 
  drop_na(X) %>% 
  drop_na(Y) %>% 
  st_as_sf(coords = c("X", "Y"), crs = st_crs(4283))

# Merge points and polygon data
da_sf_sa1 <- sf::st_join(da_sf, sa1,  join = st_intersects)
```


# 1.3 Remove data errors, create residential flag
```{r}
# Summary of category types
da_summ <- ddply(da_sf_sa1, .(CATEGORYOFDEVELOPMENT), summarise, number = length(OBJECTID))

# Residential alteration types
residential <- c('Mixed',
                 'Residential - Alterations & additions', 
                 'Residential - Alterations and additions', 
                 'Residential - New multi unit',
                 'Residential - New second occupancy',
                 'Residential - Other',
                 'Residential - Single new dwelling',
                 'Residential  Alterations and additions',
                 'Residential  New multi unit',
                 'Residential  New second occupancy',
                 'Residential  Other',
                 'Residential  Single new dwelling')

# Add on residential flag; year
da_df <- da_sf_sa1 %>% 
  mutate(date_lodged = as.Date(LODGED,'%Y/%m/%d %H:%M:%S'),
         date_determined = as.Date(DETERMINED,'%Y/%m/%d %H:%M:%S'),
         year = format(as.Date(date_lodged, format="%d/%m/%Y"),"%Y"),
         category = ifelse(CATEGORYOFDEVELOPMENT %in% residential,
                           "residential",
                           "non-residential"),
         SA2_NAME_gent = ifelse(SA2_NAME16 %in% c('Auburn - Central', 'Auburn - South', 'Auburn - North'), 'Auburn',
                                ifelse(SA2_NAME16 %in% c('Bankstown - South', 'Bankstown - North'), 'Bankstown',
                                       ifelse(SA2_NAME16 %in% c('Baulkham Hills (East)','Baulkham Hills (West) - Bella Vista',
                                                                'Eastwood - Denistone'), 'Eastwood - Baulkham Hills',
                                              ifelse(SA2_NAME16 %in% c('Maroubra - North','Maroubra - South','Maroubra - West'), 'Maroubra',
                                                     ifelse(SA2_NAME16 %in% c('Sutherland - Kirrawee', 'Oyster Bay - Como - Jannali'),
                                                            'Sutherland',
                                                            ifelse(SA2_NAME16 %in% c('Freshwater - Brookvale', 'Manly Vale - Allambie Heights'),
                                                                   'Brookvale', 
                                                                   SA2_NAME16 ) )  ) ) ) ) ) %>% 
  filter(category == "residential") %>% 
  drop_na(SA2_NAME16)

da_df$geometry <- NULL
```



############ 2. Comparing annual residential DA's ###################
# 2.1 Compare for selected gentrifying hotspots
```{r}
# Summarise DA's by SA2 area by year
da_summ_sa2 <- ddply(da_df, c('SA2_NAME_gent', 'year'), summarise,
                     count = length(OBJECTID)) %>% 
  mutate(year = as.integer(year)) %>% 
  filter(year > 2009)

# Reshape to wide format
da_summ_sa2_wide <- reshape(da_summ_sa2, idvar = "SA2_NAME_gent", timevar = "year", direction = "wide")

# Identify hotspots:
hotspots <- c('Auburn',
              'Bankstown',
              'Eastwood - Baulkham Hills',
              'Botany',
              'Brookvale',
              'Maroubra',
              'Sutherland')

da_summ_gent <- da_summ_sa2_wide %>% 
  filter(SA2_NAME_gent %in% hotspots)
```

# 2.2 Sydney-Wide scale
```{r}
# Summarise DA's by SA2 area by year
da_summ_syd <- ddply(da_df, c('GCC_CODE16', 'year'), summarise,
                     count = length(OBJECTID)) %>% 
  mutate(year = as.integer(year)) %>% 
  filter(year > 2009)

# Reshape to wide format
da_summ_syd_wide <- reshape(da_summ_syd, idvar = "GCC_CODE16", timevar = "year", direction = "wide")
```

